package com.sunsea.parkinghere.webservice.client.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-20T14:57:07.104+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://user.webservice.yelr.com/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "getName", targetNamespace = "http://user.webservice.yelr.com/", className = "com.sunsea.parkinghere.webservice.client.user.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://user.webservice.yelr.com/", className = "com.sunsea.parkinghere.webservice.client.user.GetNameResponse")
    @WebResult(name = "String", targetNamespace = "")
    public java.lang.String getName(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId
    );
}
