package com.sunsea.parkinghere.webservice.client.das;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-20T20:19:49.495+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "SwitchControlerSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SwitchControlerSoap {

    /**
     * 多路开关状态读取
     */
    @WebMethod(operationName = "ReadSwitchStatus", action = "http://tempuri.org/ReadSwitchStatus")
    @RequestWrapper(localName = "ReadSwitchStatus", targetNamespace = "http://tempuri.org/", className = "com.sunsea.parkinghere.webservice.client.das.ReadSwitchStatus")
    @ResponseWrapper(localName = "ReadSwitchStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.sunsea.parkinghere.webservice.client.das.ReadSwitchStatusResponse")
    @WebResult(name = "ReadSwitchStatusResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String readSwitchStatus(
        @WebParam(name = "RWID", targetNamespace = "http://tempuri.org/")
        java.lang.String rwid,
        @WebParam(name = "SwitchID", targetNamespace = "http://tempuri.org/")
        java.lang.String switchID
    );

    @WebMethod(action = "http://tempuri.org/test")
    @RequestWrapper(localName = "test", targetNamespace = "http://tempuri.org/", className = "com.sunsea.parkinghere.webservice.client.das.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://tempuri.org/", className = "com.sunsea.parkinghere.webservice.client.das.TestResponse")
    public void test();

    /**
     * 多路开关控制
     */
    @WebMethod(operationName = "SetSwitch", action = "http://tempuri.org/SetSwitch")
    @RequestWrapper(localName = "SetSwitch", targetNamespace = "http://tempuri.org/", className = "com.sunsea.parkinghere.webservice.client.das.SetSwitch")
    @ResponseWrapper(localName = "SetSwitchResponse", targetNamespace = "http://tempuri.org/", className = "com.sunsea.parkinghere.webservice.client.das.SetSwitchResponse")
    @WebResult(name = "SetSwitchResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String setSwitch(
        @WebParam(name = "RWID", targetNamespace = "http://tempuri.org/")
        java.lang.String rwid,
        @WebParam(name = "SwitchID", targetNamespace = "http://tempuri.org/")
        java.lang.String switchID,
        @WebParam(name = "SwitchModeSequence", targetNamespace = "http://tempuri.org/")
        java.lang.String switchModeSequence
    );
}
