package com.sunsea.parkinghere.webservice.client.das;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-20T20:19:49.506+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "SwitchControler", 
                  wsdlLocation = "http://39.108.181.184/SwitchControler.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class SwitchControler extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "SwitchControler");
    public final static QName SwitchControlerSoap = new QName("http://tempuri.org/", "SwitchControlerSoap");
    public final static QName SwitchControlerSoap12 = new QName("http://tempuri.org/", "SwitchControlerSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://39.108.181.184/SwitchControler.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SwitchControler.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.31.36:8080/SwitchControler.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SwitchControler(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SwitchControler(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SwitchControler() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SwitchControler(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SwitchControler(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SwitchControler(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SwitchControlerSoap
     */
    @WebEndpoint(name = "SwitchControlerSoap")
    public SwitchControlerSoap getSwitchControlerSoap() {
        return super.getPort(SwitchControlerSoap, SwitchControlerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SwitchControlerSoap
     */
    @WebEndpoint(name = "SwitchControlerSoap")
    public SwitchControlerSoap getSwitchControlerSoap(WebServiceFeature... features) {
        return super.getPort(SwitchControlerSoap, SwitchControlerSoap.class, features);
    }


    /**
     *
     * @return
     *     returns SwitchControlerSoap
     */
    @WebEndpoint(name = "SwitchControlerSoap12")
    public SwitchControlerSoap getSwitchControlerSoap12() {
        return super.getPort(SwitchControlerSoap12, SwitchControlerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SwitchControlerSoap
     */
    @WebEndpoint(name = "SwitchControlerSoap12")
    public SwitchControlerSoap getSwitchControlerSoap12(WebServiceFeature... features) {
        return super.getPort(SwitchControlerSoap12, SwitchControlerSoap.class, features);
    }

}
