
package com.sunsea.parkinghere.webservice.client.das;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-20T20:19:49.478+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class SwitchControlerSoap_SwitchControlerSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "SwitchControler");

    private SwitchControlerSoap_SwitchControlerSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SwitchControler.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SwitchControler ss = new SwitchControler(wsdlURL, SERVICE_NAME);
        SwitchControlerSoap port = ss.getSwitchControlerSoap12();  
        
        /*{
        System.out.println("Invoking readSwitchStatus...");
        java.lang.String _readSwitchStatus_rwid = "";
        java.lang.String _readSwitchStatus_switchID = "";
        java.lang.String _readSwitchStatus__return = port.readSwitchStatus(_readSwitchStatus_rwid, _readSwitchStatus_switchID);
        System.out.println("readSwitchStatus.result=" + _readSwitchStatus__return);


        }
        {
        System.out.println("Invoking test...");
        port.test();


        }*/
        {
        System.out.println("Invoking setSwitch...");
        java.lang.String _setSwitch_rwid = "2";
        java.lang.String _setSwitch_switchID = "2";
        java.lang.String _setSwitch_switchModeSequence = "2";
        java.lang.String _setSwitch__return = port.setSwitch(_setSwitch_rwid, _setSwitch_switchID, _setSwitch_switchModeSequence);
        System.out.println("setSwitch.result=" + _setSwitch__return);


        }

        System.exit(0);
    }

}
